# Generated by Django 2.2.7 on 2019-11-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191110_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_veg',
            field=models.BooleanField(default=True),
        ),
    ]
